controller:
  serviceType: ClusterIP
  admin:
    createSecret: true
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
  installPlugins:
    - kubernetes:4306.vc91e951ea_eb_d
    - workflow-aggregator:600.vb_57cdd26fdd7
    - git:5.5.1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

