replicaCount: 2

image:
  repository: "123456789012.dkr.ecr.us-west-2.amazonaws.com/lesson-7-django"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DJANGO_SECRET_KEY: "change-me-in-prod"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DB_NAME: "django_db"
  DB_USER: "django_user"
  DB_PASSWORD: "django_pass"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

