{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: {{ default "git" .type }}
  url: {{ .url }}
  username: {{ default "" .username }}
  password: {{ default "" .password }}
---
{{- end }}

